public class Main {
    public static void main(String[] args) {
        Plate plate = new Plate("Ceramic", 500, true);
        Cup cup = new Cup("Glass", 250, true);
        Bowl bowl = new Bowl("Porcelain", 750, true);

        plate.use();    // Output: Using the plate...
        plate.clean();  // Output: Cleaning the plate...

        cup.use();      // Output: Using the cup...
        cup.clean();    // Output: Cleaning the cup...

        bowl.use();     // Output: Using the bowl...
        bowl.clean();   // Output: Cleaning the bowl...
    }
}